#!/usr/bin/env bash
set -ex

if [ $# -lt 1 ] ; then
    echo "Usage $0 <command>" >&2
    echo "Commands:" >&2
    echo "  install [pkg_name]" >&2
    exit 1
fi

. include/git
. include/path
. include/runners

JOBS=4
PREFIX=$HOME/local
SRC_DIR=$PREFIX/src
SCRIPTS_DIR=$(abspath scripts)
INSTALLED_DIR=$(abspath .installed)

only=$2

export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig
mkdir -p $SRC_DIR

for script_name in $(ls $SCRIPTS_DIR)
do
    if [ -z $only ] || [ $only = $script_name ]
    then
        (run_install $script_name)
    fi
done
