#!/usr/bin/env bash

# ./okboomer [pkg_name]

set -ex

if [ $# -lt 1 ] ; then
    echo "Usage $0 <command>" >&2
    echo "Commands:" >&2
    echo "  install [pkg_name]" >&2
    exit 1
fi


function abspath() {
    echo "$(cd "$(dirname "$1")"; pwd -P)/$(basename "$1")"
}

. include/git

JOBS=4
PREFIX=$HOME/local
SRC_DIR=$PREFIX/src
SCRIPTS_DIR=$(abspath scripts)
INSTALLED_DIR=$(abspath .installed)

only=$2

export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig
mkdir -p $SRC_DIR

function run_install() {
    script_name=$1
    INSTALLED=$INSTALLED_DIR/$script_name
    DEPS=

    . "$SCRIPTS_DIR/$script_name"

    for dep in $DEPS
    do
        (run_install $dep)
    done

    echo "run_installing $script_name"

    cd $SRC_DIR
    download

    if [ ! -f $INSTALLED ] || [ $HEAD != $(cat $INSTALLED) ]
    then
        cd $NAME
        install
        echo $HEAD > $INSTALLED_DIR/$script_name
    fi
}

for script_name in $(ls $SCRIPTS_DIR)
do
    if [ -z $only ] || [ $only = $script_name ]
    then
        (run_install $script_name)
    fi
done
