#!/usr/bin/env bash
NAME=cpython
URL=https://github.com/python/cpython.git

function download() {
    git_clone_or_pull $URL $NAME
}

function install() {
    ./configure --prefix=$PREFIX
    make -j$JOBS
    make install
}
