#!/usr/bin/env bash

NAME=tmux
URL=https://github.com/tmux/tmux.git

function download() {
    git_clone_or_pull $URL $NAME
}

function install() {
    make clean || true
    ./autogen.sh
    ./configure --prefix=$PREFIX
    make -j$JOBS
    make install prefix=$SANDBOX_DIR
}
