#!/usr/bin/env bash

NAME=vim
URL=https://github.com/vim/vim.git

function download() {
    git_clone_or_pull $URL $NAME
}

function install() {
    make clean || true
    ./configure --prefix=$PREFIX
    make -j$JOBS
    make install prefix=$SANDBOX_DIR
}
