#!/usr/bin/env bash

function run_install() {
    # run_install <script>

    script_name=$1
    INSTALLED=$INSTALLED_DIR/$script_name
    INSTALLED_FILE_LIST="$INSTALLED.file-list"
    INSTALLED_DIR_LIST="$INSTALLED.dir-list"

    DEPS=

    . "$SCRIPTS_DIR/$script_name"

    for dep in $DEPS
    do
        (run_install $dep)
    done

    echo "run_installing $script_name"

    cd $SRC_DIR
    download

    if [ ! -f $INSTALLED ] || [ $HEAD != $(cat $INSTALLED) ]
    then
        SANDBOX_DIR=$_SANDBOX_DIR/$script_name
        mkdir -p $SANDBOX_DIR

        cd $NAME
        install

        (
            cd $SANDBOX_DIR
            find . ! -type d ! -path . > $INSTALLED_FILE_LIST
            find . -type d ! -path . | awk '{ print length(), $0 | "sort -nr" }' | awk '{ print $2 }' > $INSTALLED_DIR_LIST
        )
        cp -R $SANDBOX_DIR/* $PREFIX
        rm -rf $SANDBOX_DIR

        echo $HEAD > $INSTALLED
    fi
}

function run_uninstall() {
    # run_uninstall <script>

    script_name=$1
    INSTALLED=$INSTALLED_DIR/$script_name
    INSTALLED_FILE_LIST="$INSTALLED.file-list"
    INSTALLED_DIR_LIST="$INSTALLED.dir-list"

    (
        cd $PREFIX
        xargs rm -f < $INSTALLED_FILE_LIST
        xargs rmdir < $INSTALLED_DIR_LIST || true
    )
    rm -f $INSTALLED_DIR_LIST
    rm -f $INSTALLED_FILE_LIST
    rm -f $INSTALLED
}
